plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'me.marensovich'
version = '0.0.1-SNAPSHOT'
description = 'ITC_KIPIFIN'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    all {
        exclude group: 'commons-logging', module: 'commons-logging'
    }
}


repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation("io.github.cdimascio:dotenv-java:3.2.0")
    implementation("org.telegram:telegrambots:6.9.7.1")


}

tasks.javadoc {
    source = sourceSets.main.allJava
    options.encoding = 'UTF-8'
    options.addBooleanOption('html5', true)
    options.author = true
    options.version = true
    options.links("https://docs.oracle.com/en/java/javase/21/docs/api/") // ссылки на стандартную JavaDocs
    options.addStringOption('Xdoclint:none', '-quiet') // отключить предупреждения
}


tasks.named('test') {
    useJUnitPlatform()
}
